#!/bin/bash
# list filenames inside ~/bin directory recursively showing the full path
find $(pwd) -maxdepth 4 -type f -not -path '*/\.*' | sort
# remove -maxdepth 1 to search recursively
# -type f: find files not directories (d)
# -not -path '*/\.*' do not return .hidden_files
